### ISSUE TITLE
[Player] Subtitles are loaded for a long time in MKV format films

### ISSUE THREAD

**Issue by sini4ka08** [easably/player#13]
**Describe the bug**
When a user downloads a movie in mkv format, subtitles are downloaded to it for about 15-30 minutes.

**Screenshot**
![MKV bloked](https://user-images.githubusercontent.com/52330389/76067594-b38d2800-5fa0-11ea-835c-8592b696ecf3.png)

**Desktop (Dinosaur about 9 years old)**
OS: Windows 8.

**Comment by sini4ka08** [comment]
Abylay has the same problem. it's not about an old desktop computer.

**Comment by pavladan** [comment]
Player moved to [extension](https://github.com/easably/extension/) repository.

**Comment by pavladan** [comment]
Trying to fix this with the https://github.com/easably/extension/commit/c45519800f6a8b2d252912540087db2e0515ba7d commit

**Comment by pavladan** [comment]
We will consider what is fixed...
