### ISSUE TITLE
[Player] It is necessary to make a minimum of subtitle size, for example 10.

### ISSUE THREAD

**Issue by sini4ka08** [easably/player#7]
Now the minimum subtitle size is 1. It look like... 
![Font size](https://user-images.githubusercontent.com/52330389/75978085-d0692300-5eee-11ea-8602-9b9b50769270.png)

**Comment by pavladan** [comment]
Player moved to [extension](https://github.com/easably/extension/) repository.
Fixed in https://github.com/easably/extension/commit/466ca77b585ddd978ef6a23d0c9845eda0c170e0
