### ISSUE TITLE
[Player] Search for a word in the subtitle list

### ISSUE THREAD

**Issue by sini4ka08** [easably/player#8]
The user immediately sees the result, when entering words. It makes no sense to click on the loop, it makes sense to delete the entered text with a cross.
![Search subtitles](https://user-images.githubusercontent.com/52330389/75979604-e6c4ae00-5ef1-11ea-891d-c8ea24642079.png)

**Comment by pavladan** [comment]
Player moved to [extension](https://github.com/easably/extension/) repository.
Fixed in https://github.com/easably/extension/commit/466ca77b585ddd978ef6a23d0c9845eda0c170e0
